### ISSUE TITLE
error

### ISSUE THREAD

**Issue by durgesh-sudo** [nandy121/inshackle#1]
Trying to follow celebgram 12331195 ...
 [!] Error                         
![Kali-Linux-2020 2-vmware-amd64-2020-09-22-09-40-52](https://user-images.githubusercontent.com/71684596/93843824-d5d66100-fcb8-11ea-9fc8-f2156f75f194.png)

plz give solution for this

**Comment by nandy121** [comment]
Please go to my new account www.github.com/nandydark
